---
- hosts: all
  tasks:
    - name: disable shutdown/hibernate on closing lid
      lineinfile:
        path: /etc/systemd/logind.conf
        line: "HandleLidSwitch=ignore"
        regexp: '(#\s*)?HandleLidSwitch.*'
        firstmatch: yes
        insertafter: regex
      notify:
        - restart systemd-logind
      become: yes

    - name: install rfkill
      package:
        name: rfkill
        state: present
      become: yes
  handlers:
    - name: restart systemd-logind
      service:
        name: systemd-logind
        state: restarted 
      become: yes

  
